### PR TITLE
Cleanup specs 1.2

### PR DESCRIPTION
**Pull request by olivier-kasisto**
Cleanup specs 1.,2
Update date format to match expected values
Update outdated sample payloads

### CODE REVIEW

**Comment by bstewartny** [comment]
We need to add "locale" (language) such as "en_US", etc. into each request.  I think where we use "user_id" parameter we need to include "locale" parameter as well.  Thoughts?  Or should this also be a header?

**Comment by olivier-kasisto** [comment]
@bstewartny The update to the documentation is to specify the service as it exists today/ UUID is the field as we currently set it. It's not a new feature that needs to be built. I think we should stick to UUID as changing may impact DBS

For "locale", we currently don't send the field so we shouldn't specify it. When we implement version 1.3, we can add it. It would be a static value that match our server locale?

**Comment by olivier-kasisto** [comment]
@bstewartny I just saw and merged your pull request for the locale HTTP Header field so I added it in the specs.
I didn't change the "UUID" as it is currently used by DBS. And I don't think we should change that.

**Comment by jonbphillips123** [comment]
does @davidsawicki  need to weigh in on the date format changes?

**Comment by davidsawicki** [comment]
Thanks @jonbphillips123 -- these changes are actually reflecting my changes and our recent discussions, so we are all good!

**Pull request merged**
